# Generated by Django 3.0.6 on 2020-05-23 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('recent_status', models.CharField(max_length=100)),
                ('facebook_link', models.URLField(blank=True, db_index=True, max_length=128, unique=True, verbose_name='facebook_link')),
                ('linkedin_link', models.URLField(blank=True, db_index=True, max_length=128, unique=True, verbose_name='linkedin_link')),
                ('github_link', models.URLField(blank=True, db_index=True, max_length=128, unique=True, verbose_name='github_link')),
                ('stack_overflow_link', models.URLField(blank=True, db_index=True, max_length=128, unique=True, verbose_name='stack_overflow_link')),
                ('resume', models.FileField(upload_to=None, verbose_name='resume')),
                ('Profile_pic', models.ImageField(blank=True, null=True, upload_to='')),
                ('email', models.EmailField(max_length=254, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
