# Generated by Django 3.0.6 on 2020-05-30 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200529_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='google_sch_link',
            field=models.URLField(blank=True, db_index=True, max_length=128, unique=True, verbose_name='google_sch_link'),
        ),
        migrations.AddField(
            model_name='profile',
            name='researchgate_link',
            field=models.URLField(blank=True, db_index=True, max_length=128, unique=True, verbose_name='researchgate_link'),
        ),
    ]
