# Generated by Django 3.0.6 on 2020-05-30 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_profile_my_website_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='my_address',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
