# Generated by Django 3.0.6 on 2020-08-28 14:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_projects_work_experience'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='work_experience',
            options={'ordering': ['Company_Name']},
        ),
        migrations.RemoveField(
            model_name='work_experience',
            name='location',
        ),
        migrations.RemoveField(
            model_name='work_experience',
            name='title',
        ),
        migrations.RemoveField(
            model_name='work_experience',
            name='url',
        ),
        migrations.AddField(
            model_name='work_experience',
            name='Company_Name',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='work_experience',
            name='Duration',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='work_experience',
            name='Job_Details',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='work_experience',
            name='Job_Role',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='work_experience',
            name='Job_address',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='work_experience',
            name='Role_Type',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='work_experience',
            name='Total_Duration',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='work_experience',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
