# Generated by Django 3.0.6 on 2020-08-28 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20200828_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work_experience',
            name='Job_Details',
            field=models.TextField(max_length=800, null=True),
        ),
    ]
